title: OWEM
# description:
theme: just-the-docs
url: https://owem-wiki.github.io
logo: "/owem-source/assets/owem_small.png"
math: mathjax
enable_copy_code_button: true

callouts:
  note:
    color: purple